### ISSUE TITLE
Support for Rococo?

### ISSUE THREAD

**Issue by vikiival** [paraspell/xcm-sdk#141]
Hey I got question if ParaSpell supports Rococo?

It would nice to at least support Rococo and system parachains (AssetHub, Coretime ..)

**Comment by dudo50** [comment]
Hey @vikiival , we already support Rococo if you provide API for Rococo
eg:
await Builder(rococoAPI).to('AssetHubPolkadot').amount(10000).address('address').build() will create XCM Transfer from Rococo to AssetHubRococo

or:
await Builder(basiliskRococoApi).to('BifrostPolkadot',2030).currency('BNC').address('address').build() will create XCM Transfer from RococoBasilisk to RococoBifrost if they are connected by HRMP channel (Not sure). Notice 2030 after 'BifrostPolkadot', we allow to override ParaID manually to allow for Testnet usage (introduced in https://github.com/paraspell/xcm-sdk/issues/97).

Hope this helped. Closing for now. Let us know if there are any else questions.

With kind regards,
Team ParaSpell
