### ISSUE TITLE
Adding Polkadot Coretime chain on Rococo

### ISSUE THREAD

**Issue by poppyseedDev** [paraspell/xcm-sdk#148]
Could you add the option to teleport from Rococo relay chain to Coretime chain on Rococo?

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-coretime-rpc.polkadot.io#/explorer

**Comment by dudo50** [comment]
@poppyseedDev , thanks for your contribution, issue and PR. We are going to check this and merge asap.

**Comment by dudo50** [comment]
@poppyseedDev , we have just merged your PR. It will be released in 2 days when we switch our repository to Monorepo. I will ping you then. Thank you for your contribution.

With kind regards,
Team ParaSpell

**Comment by poppyseedDev** [comment]
Nice thanks!

**Comment by dudo50** [comment]
@poppyseedDev , your requested feature is now released in version 4.1.0.

With kind regards,
Team ParaSpell
