### ISSUE TITLE
Merge currencyID and currency

### ISSUE THREAD

**Issue by dudo50** [paraspell/xcm-sdk#16]
Merge `currencyID` and `currency` into one so developers only have to enter what node they wish to implement requires.

Eg:
Instead of `.currency('KSM').currencyID(1)`
Developer would just enter:
`.currency('KSM')` or
`.currency('1')`

By what their node would require (how they handle assets)

**Comment by dudo50** [comment]
Issue raised by suggestion of @vikiival here: https://github.com/paraspell/sdk/pull/15

**Comment by vikiival** [comment]
Nice idea!

**Comment by dudo50** [comment]
Resolved in PR https://github.com/paraspell/xcm-sdk/pull/30
