### ISSUE TITLE
Suggestion to add Polkadot API & Types as Peer Dependency

### ISSUE THREAD

**Issue by dudo50** [paraspell/xcm-sdk#23]
It was suggested to us to add Polkadot API and Types as Peer dependency for easier integration.

This can now be matter of further discussion.
```
 "@polkadot/api"
 "@polkadot/types"
```

**Comment by nohaapav** [comment]
Any ETA on this ?

**Comment by dudo50** [comment]
@nohaapav , the discussion on this matter is going to be concluded either today or tomorrow. The integration will be matter of hours then.

With kind regards,
Team ParaSpell

**Comment by dudo50** [comment]
@nohaapav , Types & API are now peer deps.
With kind regards,
Team ParaSpell

**Comment by nohaapav** [comment]
Thx guys that was quick, thx. Can you also move other polkadot deps to peer section pls :
 "@polkadot/api-base": "^9.13.2",
 "@polkadot/apps-config": "^0.124.1",

At the time of writing you had just types & api deps but generally speaking, would be great to move all deps from polkadot workspace as peer. The reason behind that is : If we already use specific polka deps (types) etc.. , we're going to end up solving conflicts .. With peer deps, works like charm out of the box ;)

**Comment by dudo50** [comment]
Thank you for suggestion @nohaapav . We will add them either today or tommorow. I will link that PR here.
With kind regards,
Team ParaSpelk

**Comment by dudo50** [comment]
Changes implemented and available in v 0.0.27. @nohaapav . Happy hacking!
