### ISSUE TITLE
Bump polkadot packages to 10.5.1

### ISSUE THREAD

**Issue by vikiival** [paraspell/xcm-sdk#34]
Hey @dudo50 & @michaeldev5,

can you please release a new version of Paraspell/sdk?
it's a bit blocking for us

Ref:
- https://github.com/kodadot/nft-gallery/pull/5864

**Comment by dudo50** [comment]
@vikiival packages bumped in the newest version 1.1.3.
Thank you for reminding us about this.
I hope this helped to resolve your issue therefore I am closing it as resolved. If it did not ping me with a comment.
