### ISSUE TITLE
unable to teleport statemine => Basilisk

### ISSUE THREAD

**Issue by daiagi** [paraspell/xcm-sdk#42]
@dudo50 

Crash:
```
client.js:100 Error: createType(Call):: Call: failed decoding polkadotXcm.limitedReserveTransferAssets:: Struct: failed on args: {"dest":"{\"_enum\":{\"__Unused0\":\"Null\",\"V2\":\"XcmV2MultiLocation\",\"__Unused2\":\"Null\",\"V3\":\"XcmV3MultiLocation\"}}","beneficiary":"{\"_enum\":{\"__Unused0\":\"Null\",\"V2\":\"XcmV2MultiLocation\",\"__Unused2\":\"Null\",\"V3\":\"XcmV3MultiLocation\"}}","assets":"{\"_enum\":{\"__Unused0\":\"Null\",\"V2\":\"XcmV2MultiassetMultiAssets\",\"__Unused2\":\"Null\",\"V3\":\"XcmV3MultiassetMultiAssets\"}}","fee_asset_item":"u32","weight_limit":"{\"_enum\":{\"Unlimited\":\"Null\",\"Limited\":\"SpWeightsWeightV2Weight\"}}"}:: Struct: failed on dest: {"_enum":{"__Unused0":"Null","V2":"XcmV2MultiLocation","__Unused2":"Null","V3":"XcmV3MultiLocation"}}:: Cannot map Enum JSON, unable to find 'V1' in __unused0, v2, __unused2, v3
    at createTypeUnsafe (type.js:13:1)
    at TypeRegistry.createTypeUnsafe (registry.js:313:1)
    at extrinsicFn (createUnchecked.js:1:1)
    at Object.decorated [as limitedReserveTransferAssets] (Decorate.js:496:1)
    at Function.transferPolkadotXCM (index.mjs:4381:1)
    at Statemine.transferPolkadotXCM (index.mjs:4441:1)
    at Statemine.transfer (index.mjs:3564:1)
    at send (index.mjs:5295:1)
    at SendBuilder.build (index.mjs:5362:1)
    at _callee$ (Teleport.vue:5:1)
```

![image](https://github.com/paraspell/xcm-sdk/assets/22791238/3cbbde93-74ca-4c10-bf1b-22894f7f6881)

as far as i can tell issue comes from 

https://github.com/paraspell/xcm-sdk/blob/65ca9fcc02e86722e8adf799d590f09ff8150f65/src/nodes/PolkadotXCMTransferImpl.ts#L12

**Comment by dudo50** [comment]
@daiagi, we are going to try resolving this asap.  Will ping you soon. Which transfer call are you using? Many thanks.

**Comment by daiagi** [comment]
Using builder API

```ts

    return paraspell 
       .Builder(api) 
       .from(Chain[fromChain.value.toUpperCase()]) 
       .currency('KSM') 
       .amount(amountValue) 
       .address(toAddress.value) 
       .build()

```

**Comment by dudo50** [comment]
@daiagi could you specify which Parachain are you transferring from? (This call is from Parachain to Relay chain)

**Comment by daiagi** [comment]
It's intended as Para to Para
Specifically between statemine and Basilisk

**Comment by daiagi** [comment]
Sorry
Wrong code snippet


This is the call

```ts

  if (telportType === TeleprtType.ParaToPara) { 
     return paraspell 
       .Builder(api) 
       .from(Chain[fromChain.value.toUpperCase()]) 
       .to(Chain[toChain.value.toUpperCase()]) 
       .currency('KSM') 
       .amount(amountValue) 
       .address(toAddress.value) 
       .build()

```

**Comment by dudo50** [comment]
As far as I am aware, there have not yet been any KSM transfers done from Statemine to Basilisk -  ref: https://kusama.subscan.io/xcm_channel/1000-2090 . 

We can try to research this for you.

**Comment by daiagi** [comment]
> As far as I am aware, there have not yet been any KSM transfers (Only USDt)

Oh I see

> We can try to research this for you.

If you can that would be lovely

**Comment by dudo50** [comment]
No problem, we will conduct research this week. You will be notified about the results asap.
With kind regards,
Team ParaSpell

**Comment by dudo50** [comment]
Dear @daiagi,
We have researched to see if transferring KSM Statemine <> Basilisk is possible.
Unfortunately, as of right now, it is not possible. Both teleport & reserve transfers are untrusted on Basilisk.
<img width="566" alt="Screenshot 2023-06-07 at 20 58 00" src="https://github.com/paraspell/xcm-sdk/assets/55763425/010ad1af-dcc5-480c-b6b9-60dd39f68298">

You can check transactions here:
- https://basilisk.subscan.io/xcm_message/kusama-22df9a8aef24da8708aac1e7ffa49ff516a189d0
- https://basilisk.subscan.io/xcm_message/kusama-62d835fe61562ca10394b024178828a6711ff233

<img width="1198" alt="Screenshot 2023-06-07 at 21 00 10" src="https://github.com/paraspell/xcm-sdk/assets/55763425/1d501833-7ef9-49e7-b123-fc53bb04e633">

We will contact the Basilisk team to see if they have any solution.
Meanwhile, we suggest you transfer KSM from Basilisk -> Kusama Relay and Kusama Relay -> Statemine (User can get prompted twice for their approval so it can be done somewhat seamlessly still)

One more thing:
We want to reward your previous efforts for hot fixing our issue with Relay -> Para transfers. 
Please send your KSM address to dudo.morhac@gmail.com we will transfer some KSM to you.

With kind regards,
Team ParaSpell

**Comment by vikiival** [comment]
cc @daiagi

**Comment by dudo50** [comment]
We were advised by Basilisk and Kusama developers, that this is a problem on Statemint side. Thus Basilisk is unable to address this at the moment.

Closing this issue until these transfers become possible.
