### ISSUE TITLE
Comprehensive list of supported Parachains

### ISSUE THREAD

**Issue by vikiival** [paraspell/xcm-sdk#43]
Hello,
It would be nice to have a list of supported Parachains like `PARACHAINS.md`

**Comment by dudo50** [comment]
This list is available here: 
https://github.com/paraspell/xcm-sdk/blob/main/docs/supportedNodes.md

Hope this resolves your issue.
Closing this for now.

**Comment by dudo50** [comment]
List is now also available in our docs: https://paraspell.github.io/docs/sdk/xcmPallet.html#list-of-implemented-polkadot-kusama-chains

**Comment by vikiival** [comment]
So may link it to readme? Its hard to find imo

**Comment by dudo50** [comment]
It is linked on top of Readme - https://github.com/paraspell/xcm-sdk#currently-supporting-46-polkadot--kusama-nodes-list-here
