### ISSUE TITLE
DOT -> STATEMINT Fails

### ISSUE THREAD

**Issue by vikiival** [paraspell/xcm-sdk#44]
https://github.com/paraspell/xcm-sdk/blob/65ca9fcc02e86722e8adf799d590f09ff8150f65/src/utils.ts#L274

![Screenshot 2023-06-28 at 12 39 50](https://github.com/paraspell/xcm-sdk/assets/22471030/275d0b19-0531-4952-99fb-7042a80a784b)

![Screenshot 2023-06-28 at 12 43 39](https://github.com/paraspell/xcm-sdk/assets/22471030/aa9d5de2-9e59-4763-aca9-c62d501ce820)

Can I ask you to fix this ASAP ? 
@dudo50 @michaeldev5

**Comment by michaeldev5** [comment]
@vikiival Should be fixed in v1.1.10

**Comment by vikiival** [comment]
It's more 1.2.0 tbh

**Comment by dudo50** [comment]
This was tested on Mainnet and works reliably. Closing this issue. See transactions below:

https://statemint.subscan.io/extrinsic/4044711-2
https://polkadot.subscan.io/extrinsic/16184921-3

**Comment by dudo50** [comment]
Call for Polkadot -> Statemint 
```js
Builder(api).to("Statemint").amount(10000000000).address("141NGS2jjZca5Ss2Nysth2stJ6rimcnufCNHnh5ExSsftn7U").build()
```               

Call for Statemint -> Polkadot

```js
Builder(api).from("Statemint").currency("DOT").amount(9000000000).address("141NGS2jjZca5Ss2Nysth2stJ6rimcnufCNHnh5ExSsftn7U").build()
```
